name: Provision Grammar Checker Portal
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    env:
      AzureClientId: ${{ secrets.AZURECLIENTID }}
      AzureClientSecret: ${{ secrets.AZURECLIENTSECRET }}
      AzureTenantId: ${{ secrets.AZURETENANTID }}
      AzureAdminName: ${{ secrets.AZUREADMINNAME }}
      AzureAdminAccess: ${{ secrets.AZUREADMINACCESS }}
      YfirlesturApiUrl: ${{ secrets.YFIRLESTURAPIURL }}
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Setup Dot Net Version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.4.22252.9
        include-prerelease: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Provision
      run: dotnet run --project .\Grammar.Checker.Portal.Web.Infrastructure.Provision\Grammar.Checker.Web.Infrastructure.Provision.csproj
